import type { Module, LearningTrack } from '@/types';

export const mockModules: Module[] = [
  {
    id: '1',
    title: 'Real-World Regex for Marketing Analysts',
    outcomes: ['Understand regex syntax', 'Apply regex to clean marketing data', 'Extract insights using regex'],
    estimatedDuration: '4 hours',
    requiredTools: ['Python', 'Jupyter Notebook'],
    proposer: 'AnalystPro',
    votes: 120,
    backers: 30,
    status: 'live',
    category: 'Data Analysis',
    coverImage: 'https://placehold.co/600x400.png',
    tags: ['regex', 'python', 'marketing', 'data cleaning'],
    rating: 4.5,
    feedbackCount: 25,
  },
  {
    id: '2',
    title: 'Ethical AI Deployment in Healthcare',
    outcomes: ['Identify ethical challenges in AI for healthcare', 'Understand regulatory frameworks', 'Develop strategies for responsible AI deployment'],
    estimatedDuration: '6 hours',
    requiredTools: ['Conceptual understanding', 'Case studies'],
    proposer: 'AI EthicsInst',
    votes: 250,
    backers: 75,
    status: 'fast-tracked',
    category: 'AI & Machine Learning',
    coverImage: 'https://placehold.co/600x400.png',
    tags: ['ai ethics', 'healthcare', 'responsible ai', 'compliance'],
    rating: 4.8,
    feedbackCount: 10,
  },
  {
    id: '3',
    title: 'Wrangling Messy Datasets in Pandas',
    outcomes: ['Handle missing data effectively', 'Clean and transform data using Pandas', 'Prepare datasets for analysis'],
    estimatedDuration: '5 hours',
    requiredTools: ['Python', 'Pandas', 'NumPy'],
    proposer: 'DataCleanerX',
    votes: 95,
    backers: 15,
    status: 'development',
    category: 'Data Science',
    coverImage: 'https://placehold.co/600x400.png',
    tags: ['pandas', 'python', 'data wrangling', 'data preprocessing'],
  },
  {
    id: '4',
    title: 'Quick-and-Dirty Dashboards in Streamlit',
    outcomes: ['Build interactive web apps for data visualization', 'Deploy Streamlit apps quickly', 'Showcase data insights effectively'],
    estimatedDuration: '3 hours',
    requiredTools: ['Python', 'Streamlit'],
    proposer: 'Sarah Analyst',
    votes: 50,
    backers: 5,
    status: 'proposed',
    category: 'Data Visualization',
    coverImage: 'https://placehold.co/600x400.png',
    tags: ['streamlit', 'python', 'dashboards', 'data apps'],
  },
];

export const mockLearningTracks: LearningTrack[] = [
  {
    id: 'lt1',
    title: 'Zero to Backend Developer',
    description: 'A comprehensive track covering 15 community-driven modules to take you from novice to backend proficiency.',
    modules: mockModules.slice(0, 2), // Simplified for mock
    creator: 'CommunityCurated',
    isMentorLed: true,
    mentor: 'ExpertDev',
    price: 199,
    coverImage: 'https://placehold.co/600x400.png',
  },
  {
    id: 'lt2',
    title: 'Data Analyst Fast-Track',
    description: 'Learn essential data analysis skills with a focus on practical application and real-world projects.',
    modules: [mockModules[0], mockModules[2]], // Simplified for mock
    creator: 'Data Insights Guild',
    isMentorLed: false,
    price: 49,
    coverImage: 'https://placehold.co/600x400.png',
  },
];
